export const IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST'
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS'
export const IMAGE_UPLOAD_FAIL = 'IMAGE_UPLOAD_FAIL'
export const IMAGE_UPLOAD_RESET = 'IMAGE_UPLOAD_RESET'